package com.vivek;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;
import java.util.concurrent.Future;

/**
 * This class was generated by Apache CXF 3.0.14
 * 2017-08-22T11:29:21.565+05:30
 * Generated source version: 3.0.14
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "ConvertTemperatureHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConvertTemperatureHttpPost {

    @WebMethod(operationName = "ConvertTemp")
    public Response<Double> convertTempAsync(
            @WebParam(partName = "Temperature", name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    String temperature,
            @WebParam(partName = "FromUnit", name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String fromUnit,
            @WebParam(partName = "ToUnit", name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String toUnit
    );

    @WebMethod(operationName = "ConvertTemp")
    public Future<?> convertTempAsync(
            @WebParam(partName = "Temperature", name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    String temperature,
            @WebParam(partName = "FromUnit", name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String fromUnit,
            @WebParam(partName = "ToUnit", name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String toUnit,
            @WebParam(name = "asyncHandler", targetNamespace = "")
                    AsyncHandler<Double> asyncHandler
    );

    @WebResult(name = "double", targetNamespace = "http://www.webserviceX.NET/", partName = "Body")
    @WebMethod(operationName = "ConvertTemp")
    public double convertTemp(
            @WebParam(partName = "Temperature", name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    String temperature,
            @WebParam(partName = "FromUnit", name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String fromUnit,
            @WebParam(partName = "ToUnit", name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    String toUnit
    );
}
