package com.vivek;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import java.util.concurrent.Future;

;

/**
 * This class was generated by Apache CXF 3.0.14
 * 2017-08-22T11:29:21.524+05:30
 * Generated source version: 3.0.14
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "ConvertTemperatureSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConvertTemperatureSoap {

    @RequestWrapper(localName = "ConvertTemp", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTemp")
    @ResponseWrapper(localName = "ConvertTempResponse", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTempResponse")
    @WebMethod(operationName = "ConvertTemp")
    public Response<ConvertTempResponse> convertTempAsync(
            @WebParam(name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    double temperature,
            @WebParam(name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit fromUnit,
            @WebParam(name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit toUnit
    );

    @RequestWrapper(localName = "ConvertTemp", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTemp")
    @ResponseWrapper(localName = "ConvertTempResponse", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTempResponse")
    @WebMethod(operationName = "ConvertTemp")
    public Future<?> convertTempAsync(
            @WebParam(name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    double temperature,
            @WebParam(name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit fromUnit,
            @WebParam(name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit toUnit,
            @WebParam(name = "asyncHandler", targetNamespace = "")
                    AsyncHandler<ConvertTempResponse> asyncHandler
    );

    @WebResult(name = "ConvertTempResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ConvertTemp", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTemp")
    @WebMethod(operationName = "ConvertTemp", action = "http://www.webserviceX.NET/ConvertTemp")
    @ResponseWrapper(localName = "ConvertTempResponse", targetNamespace = "http://www.webserviceX.NET/", className = "ConvertTempResponse")
    public double convertTemp(
            @WebParam(name = "Temperature", targetNamespace = "http://www.webserviceX.NET/")
                    double temperature,
            @WebParam(name = "FromUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit fromUnit,
            @WebParam(name = "ToUnit", targetNamespace = "http://www.webserviceX.NET/")
                    TemperatureUnit toUnit
    );
}
